sudo: required
dist: trusty

language: java
jdk:
- openjdk8

git:
  submodules: false
before_install: git submodule update --init --recursive

env: GRADLE_OPTS="-Xms1g -Xmx3g"
script: ./gradlew build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
  - rm -rf $HOME/.gradle/caches/minecraft/deobfedDeps/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email: false

after_success:
  - ./gradlew :travisPublish

deploy:
  file_glob: true
  provider: releases
  api-key: ${KEY}
  file: "./build/libs/foxguard*.jar"
  skip_cleanup: true
  on:
    tags: true